services:
  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./app:/app
      - /app/node_modules
    depends_on:
      - backend 

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5001:5000"  # Change 5000 to 5001 or any other available port
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
